/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    Core: typeof import('./src/components/console/Core.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Files: typeof import('./src/components/console/Files.vue')['default']
    IconMdiAccountGroup: typeof import('~icons/mdi/account-group')['default']
    IconMdiAccountMultiple: typeof import('~icons/mdi/account-multiple')['default']
    IconMdiAccountRemove: typeof import('~icons/mdi/account-remove')['default']
    IconMdiBackupRestore: typeof import('~icons/mdi/backup-restore')['default']
    IconMdiChip: typeof import('~icons/mdi/chip')['default']
    IconMdiCircle: typeof import('~icons/mdi/circle')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiConnection: typeof import('~icons/mdi/connection')['default']
    IconMdiConsole: typeof import('~icons/mdi/console')['default']
    IconMdiContentSave: typeof import('~icons/mdi/content-save')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IconMdiDownload: typeof import('~icons/mdi/download')['default']
    IconMdiFileDocument: typeof import('~icons/mdi/file-document')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMicrophoneOff: typeof import('~icons/mdi/microphone-off')['default']
    IconMdiPalette: typeof import('~icons/mdi/palette')['default']
    IconMdiPencil: typeof import('~icons/mdi/pencil')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    IconMdiPower: typeof import('~icons/mdi/power')['default']
    IconMdiPowerOff: typeof import('~icons/mdi/power-off')['default']
    IconMdiPowerOn: typeof import('~icons/mdi/power-on')['default']
    IconMdiPuzzle: typeof import('~icons/mdi/puzzle')['default']
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IconMdiReload: typeof import('~icons/mdi/reload')['default']
    IconMdiRestart: typeof import('~icons/mdi/restart')['default']
    IconMdiRestore: typeof import('~icons/mdi/restore')['default']
    IconMdiSend: typeof import('~icons/mdi/send')['default']
    IconMdiServer: typeof import('~icons/mdi/server')['default']
    IconMdiShieldCrown: typeof import('~icons/mdi/shield-crown')['default']
    IconMdiStop: typeof import('~icons/mdi/stop')['default']
    IconMdiUpload: typeof import('~icons/mdi/upload')['default']
    IconMdiViewDashboard: typeof import('~icons/mdi/view-dashboard')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    Other: typeof import('./src/components/console/Other.vue')['default']
    Overview: typeof import('./src/components/console/Overview.vue')['default']
    Players: typeof import('./src/components/console/Players.vue')['default']
    Plugins: typeof import('./src/components/console/Plugins.vue')['default']
    Remote: typeof import('./src/components/console/Remote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerList: typeof import('./src/components/ServerList.vue')['default']
    Terminal: typeof import('./src/components/console/Terminal.vue')['default']
  }
}
